# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    controller_factory:
        class: AppBundle\Factory\Controller
        arguments: [
            "@doctrine.orm.entity_manager",
            "@date_time_provider"
            ]
    review_controller:
        class: AppBundle\Controller\ReviewController
        factory: "controller_factory:getReviewController"
    date_time_provider:
        class: AppBundle\Provider\DateTimeProvider
    company_api:
      class: AppBundle\Api\CompanyApi
